// @flow



// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var max: number = 4000000;
var sum: number = 0;

var fib: Array<number> = []; // Initialize array!

fib[0] = 0;
fib[1] = 1;

for (var i = 2; fib[i - 1] < max; i++) {
  // Next fibonacci number = previous + one before previous
  // Translated to JavaScript:
  fib[i] = fib[i - 2] + fib[i - 1];
 console.log(fib[i]);
 
 var currentTerm: number = fib[i];
 if (currentTerm % 2 == 0) sum = sum + currentTerm;
 
}



// var previousTerm: number = 1;
// var nextTerm: number = 0;
// 
// for (var currentTerm = 2; currentTerm < max; currentTerm += nextTerm) {
// 	
// 	if (currentTerm % 2 == 0) sum = sum + currentTerm;
// 	
// 	if (currentTerm < 1000) {
// 	
// 		console.log("Current term: " +  currentTerm);
// 		console.log("Previous: " + previousTerm);
// 	
// 	}
// 	
// 	nextTerm = currentTerm + previousTerm;
// 	
// 	previousTerm = nextTerm;
// 
// }

console.log(sum);
