// @flow

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


var max: number = 4000000;
var sum: number = 0;

var fib: Array<number> = []; 

fib[0] = 0;
fib[1] = 1;

for (var i = 2; fib[i - 1] < max; i++) {
  fib[i] = fib[i - 2] + fib[i - 1];
 console.log(fib[i]);
 
 var currentTerm: number = fib[i];
 if (currentTerm % 2 == 0) sum = sum + currentTerm;
 }

console.log(sum);
